"use client";

import { Avatar, Button, Modal, VerifiedBadge } from "@/components/ui";
import { ArrowLeft, Check, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

export default function MatchConfirmPage() { const [confirmed, setConfirmed] = useState(false); return <div className="px-5 pb-28 pt-[max(1.25rem,env(safe-area-inset-top))]"><header className="flex items-center justify-between"><Link href="/matches" className="grid size-10 place-items-center rounded-full bg-white"><ArrowLeft size={19}/></Link><span className="text-sm font-bold">同行确认</span><span className="w-10"/></header><div className="mt-9 text-center"><Avatar label="禾" className="size-24 text-3xl"/><div className="mt-4 flex items-center justify-center gap-2"><h1 className="text-2xl font-black">阿禾</h1><VerifiedBadge/></div><p className="mt-2 text-sm text-ink/45">女 · 27 · 杭州 · 建筑摄影师</p></div><section className="glass mt-7 rounded-card p-5"><h2 className="font-bold">关于这次同行</h2><div className="mt-4 grid grid-cols-3 gap-2 text-center"><Stat value="92%" label="行程相似"/><Stat value="4.9" label="同行评分"/><Stat value="3 次" label="完成同行"/></div><p className="mt-5 text-sm leading-6 text-ink/60">“想慢慢骑洱海西线，早起没问题。旅行中习惯提前商量预算，也尊重彼此独处的时间。”</p></section><section className="mt-4 rounded-card bg-forest-700 p-5 text-white"><div className="flex items-center gap-2 font-bold"><ShieldCheck/>安全确认</div><ul className="mt-3 space-y-2 text-xs leading-5 text-white/70"><li>• 对方已完成实名认证</li><li>• 申请通过不代表直接入群</li><li>• 双方分别确认后，系统才创建小组</li></ul></section><Button onClick={() => setConfirmed(true)} className="mt-6 w-full bg-coral hover:bg-coral">同意同行申请</Button><Modal open={confirmed} onClose={() => setConfirmed(false)} title="你的确认已提交"><div className="text-center"><span className="mx-auto grid size-14 place-items-center rounded-full bg-forest-500 text-white"><Check/></span><p className="mt-4 text-sm leading-6 text-ink/60">阿禾也已确认。旅行小组现在可以进入了。</p><Link href="/groups/dali-crew"><Button className="mt-5 w-full">进入旅行小组</Button></Link></div></Modal></div>; }
function Stat({ value, label }: { value: string; label: string }) { return <div className="rounded-2xl bg-white p-3"><b className="block text-lg">{value}</b><span className="text-[10px] text-ink/40">{label}</span></div>; }
