"use client";

import { Avatar, Button, Modal, VerifiedBadge } from "@/components/ui";
import { members, mockRates } from "@/mocks/data";
import { ArrowLeft, Calculator, Check, MessageCircle, Plus, Send, UsersRound } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";

type Expense = { name: string; payer: string; amount: number; currency: string; split: string[] };
export default function GroupPage() {
  const [tab, setTab] = useState<"chat"|"expense"|"member">("chat"); const [open, setOpen] = useState(false); const [messages, setMessages] = useState([{ who: "阿禾", text: "我订好喜洲的民宿啦，离稻田很近。", mine: false }, { who: "我", text: "太好啦！第一天我来租车 🚲", mine: true }]); const [message, setMessage] = useState("");
  const [expenses, setExpenses] = useState<Expense[]>([{ name: "喜洲民宿", payer: "陈曦", amount: 880, currency: "CNY", split: ["陈曦","阿禾","林屿"] }, { name: "骑行租车", payer: "阿禾", amount: 18, currency: "USD", split: ["陈曦","阿禾","林屿"] }]);
  const paidCny = useMemo(() => expenses.reduce((s,e)=>s+e.amount*mockRates[e.currency],0),[expenses]); const each = paidCny / 3;
  const send = () => { if (!message.trim()) return; setMessages([...messages,{ who:"我", text:message, mine:true }]); setMessage(""); };
  return <div className="min-h-dvh pb-28 pt-[max(1.25rem,env(safe-area-inset-top))]"><header className="page-pad flex items-center justify-between"><Link href="/trips/yunnan-summer" className="grid size-10 place-items-center rounded-full bg-white"><ArrowLeft size={19}/></Link><div className="text-center"><b className="block text-sm">去大理吹风小队</b><span className="text-[10px] text-forest-500">3 人 · 已双向确认</span></div><div className="flex -space-x-2">{members.slice(0,2).map(m=><Avatar key={m.id} label={m.avatar} className="size-8 border-2 border-sand"/>)}</div></header><div className="mx-5 mt-5 flex rounded-full bg-ink/5 p-1">{[["chat","群聊",MessageCircle],["expense","AA 记账",Calculator],["member","成员",UsersRound]].map(([id,label,Icon]) => { const I=Icon as typeof MessageCircle; return <button key={id as string} onClick={()=>setTab(id as typeof tab)} className={`pill flex flex-1 items-center justify-center gap-1.5 ${tab===id?"bg-white shadow-sm":"text-ink/45"}`}><I size={15}/>{label as string}</button>})}</div>
    {tab === "chat" && <div className="page-pad mt-6"><p className="text-center text-[10px] text-ink/35">今天 14:20 · 消息通过 Supabase Realtime 接口适配</p><div className="mt-6 space-y-4">{messages.map((m,i)=><div key={i} className={`flex gap-2 ${m.mine?"justify-end":""}`}>{!m.mine&&<Avatar label={m.who}/>}<div><p className={`mb-1 text-[10px] text-ink/35 ${m.mine?"text-right":""}`}>{m.who}</p><p className={`max-w-[280px] rounded-2xl px-4 py-3 text-sm leading-6 ${m.mine?"rounded-tr-sm bg-ink text-white":"rounded-tl-sm bg-white"}`}>{m.text}</p></div></div>)}</div><div className="fixed bottom-24 left-1/2 z-30 flex w-[calc(100%-40px)] max-w-[440px] -translate-x-1/2 gap-2 rounded-full bg-white p-2 shadow-glass"><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="说点什么…" className="min-w-0 flex-1 bg-transparent pl-3 text-sm outline-none"/><button onClick={send} className="grid size-10 place-items-center rounded-full bg-coral text-white"><Send size={17}/></button></div></div>}
    {tab === "expense" && <div className="page-pad mt-6"><div className="grain relative overflow-hidden rounded-card bg-gradient-to-br from-forest-700 to-lake-500 p-5 text-white"><p className="text-xs text-white/60">本组累计支出（折合 CNY）</p><p className="mt-2 text-3xl font-black">¥{paidCny.toFixed(2)}</p><div className="mt-5 grid grid-cols-2 gap-3 text-xs"><span className="rounded-2xl bg-white/10 p-3">你已支付<b className="mt-1 block text-lg">¥880</b></span><span className="rounded-2xl bg-white/10 p-3">人均支出<b className="mt-1 block text-lg">¥{each.toFixed(2)}</b></span></div></div><div className="mt-5 space-y-3">{expenses.map((e,i)=><div key={i} className="rounded-2xl bg-white p-4"><div className="flex justify-between"><div><b className="text-sm">{e.name}</b><p className="mt-1 text-[11px] text-ink/40">{e.payer} 支付 · {e.split.length} 人均摊</p></div><b>{e.currency} {e.amount}</b></div></div>)}</div><button onClick={()=>setOpen(true)} className="mt-4 flex w-full items-center justify-center gap-2 rounded-full border border-dashed border-lake-500/40 py-4 text-sm font-bold text-lake-500"><Plus size={17}/>添加消费</button><p className="mt-4 text-[10px] leading-4 text-ink/35">MVP 使用 Mock 汇率，仅做账目计算，不涉及真实支付、代收或转账。</p></div>}
    {tab === "member" && <div className="page-pad mt-6 space-y-3">{members.map(m=><div key={m.id} className="flex items-center gap-3 rounded-2xl bg-white p-4"><Avatar label={m.avatar}/><div className="flex-1"><div className="flex items-center gap-2"><b className="text-sm">{m.name}</b>{m.verified&&<VerifiedBadge compact/>}</div><p className="text-[10px] text-ink/40">{m.role}</p></div><Check size={16} className="text-forest-500"/></div>)}</div>}
    <Modal open={open} onClose={()=>setOpen(false)} title="添加一笔消费"><div className="space-y-3"><input id="expense-name" placeholder="消费名称" className="w-full rounded-2xl bg-white p-4 outline-none"/><div className="flex gap-2"><input id="expense-amount" type="number" placeholder="金额" className="min-w-0 flex-1 rounded-2xl bg-white p-4 outline-none"/><select id="expense-currency" className="rounded-2xl bg-white px-3"><option>CNY</option><option>USD</option><option>JPY</option></select></div><p className="text-xs text-ink/45">默认由陈曦支付，三位成员平均分摊</p><Button onClick={()=>{setExpenses([...expenses,{name:"新增消费",payer:"陈曦",amount:120,currency:"CNY",split:["陈曦","阿禾","林屿"]}]);setOpen(false)}} className="w-full">保存消费</Button></div></Modal>
  </div>;
}
