"use client";

import { Button } from "@/components/ui";
import { ArrowLeft, Check, PenLine, Send, Sparkles } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

const generated = `# 在大理，把日子过成一阵风\n\n四天里，我们沿着洱海骑行，也在苍山的云里慢慢走。最值得记下的不是完成了多少景点，而是每个人都能自在地调整节奏。\n\n## 交通\n落地后拼车进古城最方便，洱海西线更推荐自行车。\n\n## 景点\n喜洲适合早上抵达，苍山记得准备一件防风外套。\n\n## 花费\n本次三人合计约 ¥1,009.28，住宿是主要支出。`;
export default function ReviewPage(){const [mode,setMode]=useState("整篇");const [text,setText]=useState("");const [visibility,setVisibility]=useState("公开");const [published,setPublished]=useState(false);const generate=async()=>{setText("正在整理沿途的风景与账单…");try{const r=await fetch("/api/ai/travelogue",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({mode})});const j=await r.json();setText(j.markdown||generated)}catch{setText(generated)}}; return <div className="px-5 pb-28 pt-[max(1.25rem,env(safe-area-inset-top))]"><header className="flex items-center justify-between"><Link href="/trips/yunnan-summer/live" className="grid size-10 place-items-center rounded-full bg-white"><ArrowLeft size={19}/></Link><span className="text-sm font-bold">游后回顾</span><span className="w-10"/></header><section className="mt-9"><span className="grid size-12 place-items-center rounded-2xl bg-coral text-white"><Sparkles/></span><h1 className="mt-5 text-3xl font-black">把这一路，写成<br/>下一位旅人的灵感</h1><p className="mt-3 text-sm leading-6 text-ink/50">AI 会结合实际路线、POI、花费和你的心得生成初稿。</p></section><div className="mt-6 flex gap-2">{["整篇","交通","景点","餐厅","商场"].map(m=><button key={m} onClick={()=>setMode(m)} className={`pill ${mode===m?"bg-ink text-white":"bg-white"}`}>{m}</button>)}</div><Button onClick={generate} className="mt-4 w-full bg-lake-500"><Sparkles size={18}/>生成{mode}攻略</Button>{text&&<div className="mt-5"><div className="mb-2 flex items-center gap-2 text-xs font-bold text-ink/50"><PenLine size={14}/>可编辑的 Markdown 初稿</div><textarea value={text} onChange={e=>setText(e.target.value)} className="min-h-[360px] w-full rounded-card bg-white p-5 text-sm leading-7 outline-none"/><div className="mt-4"><p className="mb-2 text-xs font-bold text-ink/50">发布可见性</p><div className="flex gap-2">{["公开","仅好友","仅自己"].map(v=><button key={v} onClick={()=>setVisibility(v)} className={`pill flex-1 ${visibility===v?"bg-ink text-white":"bg-white"}`}>{v}</button>)}</div></div><Button onClick={()=>setPublished(true)} className="mt-5 w-full bg-coral hover:bg-coral">{published?<><Check/>已发布到社区</>:<><Send size={17}/>一键发布</>}</Button></div>}</div>}
